In [237]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/bank-customer-churn/Customer-Churn-Records.csv


In [238]:
df = pd.read_csv('/kaggle/input/bank-customer-churn/Customer-Churn-Records.csv')

In [239]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Complain  Satisfaction Score Card Type  \
0        101348.88       1         1                   2   DIAMOND   
1        112542.58       0         1                   3   DIAMOND   
2        113931.57       1         1                   3   DIAMOND   
3         93826.63       0         0                   5      GOLD   
4         79084.10       0         0                   5      GOLD   

   Point Earned  
0           464  
1           456  
2           377  
3           350  
4           425

In [240]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Card Type', 'Point Earned'],
      dtype='object')

In [241]:
df.shape

(10000, 18)

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   RowNumber           10000 non-null  int64  
 1   CustomerId          10000 non-null  int64  
 2   Surname             10000 non-null  object 
 3   CreditScore         10000 non-null  int64  
 4   Geography           10000 non-null  object 
 5   Gender              10000 non-null  object 
 6   Age                 10000 non-null  int64  
 7   Tenure              10000 non-null  int64  
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64  
 10  HasCrCard           10000 non-null  int64  
 11  IsActiveMember      10000 non-null  int64  
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64  
 14  Complain            10000 non-null  int64  
 15  Satisfaction Score  10000 non-null  int64  
 16  Card 

In [243]:
df.isnull().sum().sum()

0

In [244]:
df.duplicated().sum()

0

In [245]:
df.values

array([[1, 15634602, 'Hargrave', ..., 2, 'DIAMOND', 464],
       [2, 15647311, 'Hill', ..., 3, 'DIAMOND', 456],
       [3, 15619304, 'Onio', ..., 3, 'DIAMOND', 377],
       ...,
       [9998, 15584532, 'Liu', ..., 3, 'SILVER', 564],
       [9999, 15682355, 'Sabbatini', ..., 2, 'GOLD', 339],
       [10000, 15628319, 'Walker', ..., 3, 'DIAMOND', 911]], dtype=object)

In [246]:
df.drop(columns="RowNumber",inplace=True)

In [247]:
df.drop(columns=["CustomerId","Surname",])

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  Complain  \
0             1               1        101348.88       1         1   
1             0               1        112542.58       0         1   
2             1               0        113931.57       1         1   
3             0               0         93826.63       0         0   
4             1               1         79084.10       0         0   
...         ...             ...              ...     ...       ...   
9995          1               0         96270.64       0         0   
9996          1               1        101699.77       0         0   
9997          0               1         42085.58       1         1   
9998          1               0         92888.52       1         1   
9999          1               0         38190.78       0         0   

      Satisfaction Score Card Type  Point Earned  
0                      2   DIAMOND           464  
1                      3   DIAMOND           456  
2                      3   DIAMOND           377  
3                      5      GOLD           350  
4                      5      GOLD           425  
...                  ...       ...           ...  
9995                   1   DIAMOND           300  
9996                   5  PLATINUM           771  
9997                   3    SILVER           564  
9998                   2      GOLD           339  
9999                   3   DIAMOND           911  

[10000 rows x 15 columns]

In [248]:
df.sample()

CustomerId Surname  CreditScore Geography Gender  Age  Tenure  \
8434    15755330  Forbes          512   Germany   Male   41       7   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
8434  122403.24              1          0               1          37439.9   

      Exited  Complain  Satisfaction Score Card Type  Point Earned  
8434       1         1                   2   DIAMOND           681

In [249]:
df["Complain"].unique()

array([1, 0])

In [250]:
df["Exited"].unique()

array([1, 0])

In [251]:
df["Satisfaction Score"].unique()

array([2, 3, 5, 4, 1])

In [252]:
df["Card Type"].unique()

array(['DIAMOND', 'GOLD', 'SILVER', 'PLATINUM'], dtype=object)

In [253]:
df["HasCrCard"].unique()

array([1, 0])

In [254]:
df["IsActiveMember"].unique()

array([1, 0])

In [255]:
df["NumOfProducts"].unique()

array([1, 3, 2, 4])

In [256]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [257]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [258]:
df["Tenure"].unique()

array([ 2,  1,  8,  7,  4,  6,  3, 10,  5,  9,  0])

In [259]:
df.drop(columns=["CustomerId","Surname"],inplace=True)

In [260]:
df.shape

(10000, 15)

In [261]:
df.sample()

CreditScore Geography Gender  Age  Tenure   Balance  NumOfProducts  \
8624          745   Germany   Male   35       4  98270.34              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  Complain  \
8624          1               0        133617.43       0         0   

      Satisfaction Score Card Type  Point Earned  
8624                   5   DIAMOND           271

In [262]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

In [263]:
transformer = ColumnTransformer(
    transformers=[
        ("tnf1", OrdinalEncoder(), ["Gender"]),
        ("tnf2", OneHotEncoder(sparse=False,drop='first'), ["Geography"]),
        ("tnf3", OneHotEncoder(sparse=False,drop='first'), ["Tenure"]),
        ("tnf4", OneHotEncoder(sparse=False,drop='first'), ["NumOfProducts"]),
        ("tnf5", OneHotEncoder(sparse=False,drop='first'), ["HasCrCard"]),
        ("tnf6", OneHotEncoder(sparse=False,drop='first'), ["IsActiveMember"]),
        ("tnf7", OneHotEncoder(sparse=False,drop='first'), ["Complain"]),
        ("tnf8", OneHotEncoder(sparse=False,drop='first'), ["Satisfaction Score"]),
        ("tnf9", OrdinalEncoder(), ["Card Type"]),
    ],
    remainder='passthrough', 
)

In [264]:
X = df.drop(columns="Exited")
Y = df["Exited"]

In [265]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [266]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_outp

In [267]:
X_train

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        6.4716080e+04, 8.6200000e+02],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.5841485e+05,
        1.3188646e+05, 8.0700000e+02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        9.9661460e+04, 2.6600000e+02],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.9503307e+05, 7.3100000e+02],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0299404e+05,
        1.7668016e+05, 2.8900000e+02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.5131637e+05, 6.6000000e+02]])

In [268]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Define the model
model = RandomForestClassifier(random_state=42)

# Create a pipeline combining preprocessing and model
pipeline = Pipeline(steps=[('model', model)])

# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Predictions on the testing data
y_pred = pipeline.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.999

Confusion Matrix:
 [[1616    1]
 [   1  382]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1617
           1       1.00      1.00      1.00       383

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000



In [269]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load your dataset
df = pd.read_csv('/kaggle/input/bank-customer-churn/Customer-Churn-Records.csv')

# Separate features and target variable
X = df.drop(columns=['Exited'])  # Features
y = df['Exited']  # Target variable

# Define categorical and numerical features
categorical_features = ['Gender', 'Geography', 'HasCrCard', 'IsActiveMember', 'Complain', 'Card Type']
numerical_features = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing pipeline for numerical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),  # Impute missing values with mean
    ('scaler', StandardScaler())  # Scale numerical features
])

# Preprocessing pipeline for categorical features
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Impute missing values with most frequent
    ('onehot', OneHotEncoder(drop='first'))  # One-hot encode categorical features, dropping the first category
])

# Combine preprocessing for numerical and categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Define the model
model = RandomForestClassifier(random_state=42)

# Create a pipeline combining preprocessing and model
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('model', model)])

# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Predictions on the testing data
y_pred = pipeline.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.999

Confusion Matrix:
 [[1606    1]
 [   1  392]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1607
           1       1.00      1.00      1.00       393

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

